# Generated by Django 3.1.7 on 2021-03-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_employees_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
